### ISSUE TITLE
Update app icon.

### ISSUE THREAD

**Issue by derek-boman** [JoiaApp/joia_ios#10]
New app icon. LMK if this size does not work, or if I need to provide other sizes.

![social_opal - brush - eyes open](https://cloud.githubusercontent.com/assets/17180771/22009028/77b02c90-dc3d-11e6-8558-985388d438bf.png)

**Comment by joshbodily** [comment]
Size should be fine.  I'll update.

**Comment by joshbodily** [comment]
This is addressed w/ 1.0.8.  Please verify 🙏 

<img width="487" alt="screen shot 2017-04-26 at 9 33 26 pm" src="https://cloud.githubusercontent.com/assets/6953200/25466804/05d49488-2ac8-11e7-93ca-a9ec960de53d.png">

**Comment by derek-boman** [comment]
Verified. Looks pretty good. Although it looks like there's a sliver of black along the top edge. I wonder if the image isn't quite square or something else seems a little off.
