### ISSUE TITLE
Arrow Icons

### ISSUE THREAD

**Issue by derek-boman** [JoiaApp/joia_ios#11]
@joshbodily All the icons in a various colors (including the white back arrow you need) can be found here: https://drive.google.com/drive/u/2/folders/0B7czuBXs1J1IcWhRZVdtNm9FRTQ

**Comment by joshbodily** [comment]
Nice, thanks 👍

**Comment by joshbodily** [comment]
This is addressed w/ 1.0.8.  Please verify 🙏
