### ISSUE TITLE
Keyboard overlapping prompt selector

### ISSUE THREAD

**Issue by derek-boman** [JoiaApp/joia_ios#3]
**Steps**
1. In Write, select the Prompt selector
2. tap the type area

The keyboard overlaps the prompt selector and you are stuck. You cannot lower the keyboard or continue on in the flow.

**Solution**
Selecting outside of the Prompt Selector should make the selector retract. I can probably think of other solutions we could do too. Open to thoughts here.

@joshbodily

**Comment by derek-boman** [comment]
The `mentions` button should also raise with the keyboard.

**Comment by derek-boman** [comment]
I guess this is more likely to happen if you reverse the steps above actually.

**Comment by joshbodily** [comment]
Could repro.  I'll think of a fix.  Simplest might be to just dismiss mentions when keyboard comes up.

**Comment by joshbodily** [comment]
This is addressed w/ 1.0.8.  Please verify 🙏
