### ISSUE TITLE
Email mention / Use email keyboard

### ISSUE THREAD

**Issue by derek-boman** [JoiaApp/joia_ios#8]
In the email mention popup we should use the alternate email keyboard on iOS. This has an @ symbol by default and makes it easier for typing email addresses.

![image](https://cloud.githubusercontent.com/assets/17180771/21836426/5bf32de6-d782-11e6-9602-5c8a393ba116.png)

**Comment by joshbodily** [comment]
Fixed in build 6

<img width="432" alt="screen shot 2017-01-15 at 5 31 58 pm" src="https://cloud.githubusercontent.com/assets/6953200/21967674/aa6883e4-db48-11e6-8007-76419b76956a.png">

**Comment by derek-boman** [comment]
That's perfect. :shipit:
