### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by derek-boman** [JoiaApp/joia_ios#9]
I noticed when I wrote a message it let me type an emoji but when I look at the message in the Journal the emoji is now a Chinese character. Can we add support for Emoji throughout the app? I have a feeling that a lot of messages will include emoji.

![image](https://cloud.githubusercontent.com/assets/17180771/21836481/ba46a454-d782-11e6-94ba-6be3bce93c31.png)

**Comment by joshbodily** [comment]
Server issues, fixed w/ https://github.com/JoiaApp/joia_server/commit/a2dc7a4edc8251de5204882ab8be8e2a4c334f46

<img width="432" alt="screen shot 2017-01-15 at 5 27 45 pm" src="https://cloud.githubusercontent.com/assets/6953200/21967636/29c596be-db48-11e6-936a-9bda5bea2941.png">

**Comment by derek-boman** [comment]
That looks good too. Can you test one of newer emojis in iOS10 also? Otherwise :shipit:

**Comment by joshbodily** [comment]
Fixed
